ignore-ghpages: &ignore-ghpages
  filters:
    branches:
      ignore:
        - gh-pages

version: 2
jobs:
  build-test-deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker image
          no_output_timeout: 2.0h
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./src/Docker/build.sh
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push insighttoolkit/itk-js:latest
            else
              docker pull insighttoolkit/itk-js:latest
              ./src/Docker/build.sh --cache-from=insighttoolkit/itk-js:latest
            fi
      - run:
          name: Install Node packages
          command: |
            npm install
      - run:
          name: Build
          command: |
            npm run build
      - run:
          name: Test
          command: |
            google-chrome --version
            npm run test
      - deploy:
          name: Publish docs
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git config --global user.name "Circle CI"
              git config --global user.email "robot@itk.org"
              npm run doc:publish
            fi

  build-test-node-example:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: Test Node.js example
          no_output_timeout: 0.5h
          command: |
            cd examples/Node.js
            npm install
            npm run test

  build-test-webpack-example:
    machine: true
    steps:
      - checkout
      - run:
          name: Test Webpack example
          no_output_timeout: 0.5h
          command: |
            cd examples/Webpack
            npm install
            npm run build
            npm run test

workflows:
    version: 2
    build-test-deploy:
      jobs:
        - build-test-deploy:
            filters:
              branches:
                ignore:
                  - gh-pages
    build-test-examples:
      jobs:
        - build-test-node-example:
            <<: *ignore-ghpages
        - build-test-webpack-example:
            <<: *ignore-ghpages
